version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/.github/actions/stage"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
