# Extra dependencies not included in the main Chromium source archive, and
# additional build utilities to replace Google-provided ones.
# Do note that utilities in here can be swapped with user-provided versions.

# Uses a heavily modified syzygy code base to build swapimport.exe
# Disabled import reordering for now since this is too much work to maintain
#[third_party/syzygy]
#version = bd0e67f571063e18e7200c72e6152a3a7e4c2a6d
#url = https://github.com/Eloston/syzygy/archive/{version}.tar.gz
#download_filename = syzygy-{version}.tar.gz
#strip_leading_dirs = syzygy-{version}

# Use a pre-built LLVM toolchain from LLVM for convenience
# Developer notes:
# * Releases of LLVM are available as "Clang for Windows (64-bit)" on LLVM's download page.
# * If the current stable version of LLVM is causing problems with the build, try
#   matching Google's LLVM version (defined by the `CLANG_REVISION` variable in
#   tools/clang/scripts/update.py by downloading a snapshot build at the version specified
#   by `CLANG_REVISION` and `VERSION` constants in `tools/clang/scripts/update.py`.
#   For example, revision 123456 of LLVM 9.8.7 64-bit Windows would be:
#   `http://prereleases.llvm.org/win-snapshots/LLVM-9.8.7-r123456-win64.exe`
#   (link derived from [LLVM Snapshot Builds](http://llvm.org/builds/))
[llvm]
version = 22.1.2
url = https://github.com/llvm/llvm-project/releases/download/llvmorg-%(version)s/LLVM-%(version)s-Linux-X64.tar.xz
download_filename = LLVM-%(version)s-Linux-X64.tar.xz
sha256 = ff32497b6801267ee427bc69cdaeecfb2d19578af8c2a942e864c45215f9a2ac
output_path = third_party/llvm-build/Release+Asserts
strip_leading_dirs = LLVM-%(version)s-Linux-X64

# Pre-built Ninja (build system)
[ninja]
version = 1.13.2
url = https://github.com/ninja-build/ninja/releases/download/v%(version)s/ninja-linux.zip
download_filename = ninja-linux-%(version)s.zip
sha256 = 5749cbc4e668273514150a80e387a957f933c6ed3f5f11e03fb30955e2bbead6
extractor = 7z
output_path = third_party/ninja

# 7-Zip for Linux
# Used by create_installer_archive.py for creating Windows installer packages
[7zip-linux]
version = 2600
url = https://www.7-zip.org/a/7z%(version)s-linux-x64.tar.xz
download_filename = 7z%(version)s-linux-x64.tar.xz
sha256 = c74dc4a48492cde43f5fec10d53fb2a66f520e4a62a69d630c44cb22c477edc6
output_path = third_party/lzma_sdk/bin/host_platform

# Pre-built Node.JS (LTS)
[nodejs]
version = 24.12.0
url = https://nodejs.org/dist/v%(version)s/node-v%(version)s-linux-x64.tar.xz
download_filename = node-v%(version)s-linux-x64.tar.xz
sha256 = bdebee276e58d0ef5448f3d5ac12c67daa963dd5e0a9bb621a53d1cefbc852fd
output_path = third_party/node/linux/node-linux-x64
strip_leading_dirs=node-v%(version)s-linux-x64

# esbuild
[esbuild]
version = 0.25.1
url = https://registry.npmjs.org/@esbuild/linux-x64/-/linux-x64-%(version)s.tgz
download_filename = esbuild-linux-x64-%(version)s.tar.gz
sha256 = a3972c20d19545792ba6c6abe564b61c91f66cfa242ff9bffd9e5d59c65452e5
output_path = third_party/devtools-frontend/src/third_party/esbuild
strip_leading_dirs=package

# DirectX-Headers
[directx-headers]
version = 62c23d5ec700659453c6fe89d296554b2a5e7edc
url = https://github.com/microsoft/DirectX-Headers/archive/%(version)s.zip
download_filename = directx-headers-%(version)s.zip
extractor = 7z
output_path = third_party/microsoft_dxheaders/src
strip_leading_dirs=DirectX-Headers-%(version)s

# Webauthn-Headers
[webauthn]
version = c3ed95fd7603441a0253c55c14e79239cb556a9f
url = https://github.com/microsoft/webauthn/archive/%(version)s.zip
download_filename = webauthn-%(version)s.zip
extractor = 7z
output_path = third_party/microsoft_webauthn/src
strip_leading_dirs=webauthn-%(version)s

# Rust
[rust-x64]
version = 2026-01-30
url = https://static.rust-lang.org/dist/%(version)s/rust-nightly-x86_64-unknown-linux-gnu.tar.xz
download_filename = rust-nightly-%(version)s-x86_64-unknown-linux-gnu.tar.xz
sha256 = 17bfbf700be4bdf576957b6bf4499b685f924f21cf6aba3f2e3d0980da75d916
output_path = third_party/rust-toolchain-x64
strip_leading_dirs=rust-nightly-x86_64-unknown-linux-gnu
[rust-x86]
version = 2026-01-30
url = https://static.rust-lang.org/dist/%(version)s/rust-nightly-i686-unknown-linux-gnu.tar.xz
download_filename = rust-nightly-%(version)s-i686-unknown-linux-gnu.tar.xz
sha256 = 82c5115bb225267e6de8530526dd4deb8231db11931916072c315dec42fe0c48
output_path = third_party/rust-toolchain-x86
strip_leading_dirs=rust-nightly-i686-unknown-linux-gnu
[rust-arm]
version = 2026-01-30
url = https://static.rust-lang.org/dist/%(version)s/rust-nightly-aarch64-unknown-linux-gnu.tar.xz
download_filename = rust-nightly-%(version)s-aarch64-unknown-linux-gnu.tar.xz
sha256 = 702d3877184118e5f9240198147fb090cfc1df4baa829f549c3adc34577401c1
output_path = third_party/rust-toolchain-arm
strip_leading_dirs=rust-nightly-aarch64-unknown-linux-gnu
[rust-std-windows-x64]
version = 2026-01-30
url = https://static.rust-lang.org/dist/%(version)s/rust-std-nightly-x86_64-pc-windows-msvc.tar.xz
download_filename = rust-std-nightly-%(version)s-x86_64-pc-windows-msvc.tar.xz
sha256 = 20bfb2b1c466fdea16302b405fe7d1c6430ce32df5b7fbeab0bd1b6d6cb932cb
output_path = third_party/rust-std-windows-x64
strip_leading_dirs=rust-std-nightly-x86_64-pc-windows-msvc
[rust-std-windows-x86]
version = 2026-01-30
url = https://static.rust-lang.org/dist/%(version)s/rust-std-nightly-i686-pc-windows-msvc.tar.xz
download_filename = rust-std-nightly-%(version)s-i686-pc-windows-msvc.tar.xz
sha256 = 5a7cbf147fc8b0c461a3feea8f64a48a7fbd9121d91167e2ae6b33dc7175ff4e
output_path = third_party/rust-std-windows-x86
strip_leading_dirs=rust-std-nightly-i686-pc-windows-msvc
[rust-std-windows-arm]
version = 2026-01-30
url = https://static.rust-lang.org/dist/%(version)s/rust-std-nightly-aarch64-pc-windows-msvc.tar.xz
download_filename = rust-std-nightly-%(version)s-aarch64-pc-windows-msvc.tar.xz
sha256 = 05600e4ee83db294448dd3b2341334f421980e509e5a5ff2ed44fa78060110d5
output_path = third_party/rust-std-windows-arm
strip_leading_dirs=rust-std-nightly-aarch64-pc-windows-msvc
[rust-windows-create]
version = 0.52.0
url = https://github.com/microsoft/windows-rs/archive/refs/tags/%(version)s.zip
download_filename = rust-windows-create-%(version)s.zip
sha512 = b505d45dfa201b0b2bf18aecea549fe72b60fbc7a2cb83d9319363e550585072cf87ce543ecf9e39d951dda2e60fcf3755bd75ead7096efdfa700f5faf781339
extractor = 7z
output_path = third_party/rust/chromium_crates_io/vendor