name: 'Prepare Build Environment'
description: 'Checkout, install deps, setup python and npm'
inputs:
  python-version:
    description: 'Python version'
    default: '3.12'
  x86:
    description: 'Building for x86 architecture'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: Free Disk Space
      uses: BRAINSia/free-disk-space@v2
      with:
        tool-cache: false
        mandb: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: false

    - name: Install System Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y zstd p7zip-full pkg-config libglib2.0-dev libfuse2 libfuse2t64 libnss3-dev libcups2-dev libpci-dev libdrm-dev libxkbcommon-dev gperf libkrb5-dev

    - name: Install 32-bit Development Libraries
      if: ${{ inputs.x86 == 'true' }}
      shell: bash
      run: |
        echo "Installing 32-bit development libraries for x86 cross-compilation..."
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y libc6-dev-i386 linux-libc-dev:i386 gcc-multilib g++-multilib

    - name: Prepare /mnt Build Directory
      shell: bash
      run: |
        set -e

        # Create /mnt build directory with proper ownership
        STORAGE_DIR="/mnt/chromium-build"

        echo "Creating build directory: ${STORAGE_DIR}"
        sudo mkdir -p "${STORAGE_DIR}"

        # Set ownership to current user
        CURRENT_USER=$(whoami)
        CURRENT_GROUP=$(id -gn)
        echo "Setting ownership to ${CURRENT_USER}:${CURRENT_GROUP}"
        sudo chown "${CURRENT_USER}:${CURRENT_GROUP}" "${STORAGE_DIR}"

        # Set permissions
        sudo chmod 755 "${STORAGE_DIR}"

        # Verify
        echo "Directory created successfully:"
        ls -ld "${STORAGE_DIR}"

        # Test write permissions
        if touch "${STORAGE_DIR}/.write-test" 2>/dev/null; then
          echo "[PASS] Write test successful"
          rm "${STORAGE_DIR}/.write-test"
        else
          echo "[FAIL] Write test failed"
          exit 1
        fi

        echo "Get CPU Info:"
        sudo lscpu

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Stage Dependencies
      shell: bash
      run: npm install
      working-directory: ./.github/actions/stage

    - name: Copy Workspace to /mnt
      shell: bash
      run: |
        set -e

        STORAGE_DIR="/mnt/chromium-build"

        echo "Copying workspace from ${GITHUB_WORKSPACE} to ${STORAGE_DIR}"
        cp -r "${GITHUB_WORKSPACE}/"* "${GITHUB_WORKSPACE}/".* "${STORAGE_DIR}/" 2>/dev/null || true