name: 'Prepare Build Environment'
description: 'Checkout, install deps, setup python and npm'
inputs:
  python-version:
    description: 'Python version'
    default: '3.12'
runs:
  using: "composite"
  steps:
    - name: Free Disk Space
      uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.1
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        docker-images: true

    - name: Install System Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y p7zip-full pkg-config libglib2.0-dev libfuse2 libfuse2t64 libnss3-dev libcups2-dev libpci-dev libdrm-dev libxkbcommon-dev

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Stage Dependencies
      shell: bash
      run: npm install
      working-directory: ./.github/actions/stage