name: build-x86
on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: read

concurrency:
  group: build-x86-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/prepare
        with:
          x86: true
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: false
          from_artifact: false
          x86: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}

  build-2:
    needs: build-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/prepare
        with:
          x86: true
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
          x86: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}

  build-3:
    needs: build-2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/prepare
        with:
          x86: true
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
          x86: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}

  build-4:
    needs: build-3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/prepare
        with:
          x86: true
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
          x86: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}

  build-5:
    needs: build-4
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/prepare
        with:
          x86: true
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
          x86: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}

  build-6:
    needs: build-5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/prepare
        with:
          x86: true
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
          x86: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}

  build-7:
    needs: build-6
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/prepare
        with:
          x86: true
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
          x86: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}

  build-8:
    needs: build-7
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      - uses: ./.github/actions/prepare
        with:
          x86: true
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ join(needs.*.outputs.finished) }}
          from_artifact: true
          x86: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}

  complete:
    needs: build-8
    runs-on: ubuntu-latest
    steps:
      - name: Ensure build finished
        run: |
          if [ "${{ needs.build-8.outputs.finished }}" != "true" ]; then
            echo "Build did not finish after 8 stages."
            exit 1
          fi
