name: Pre Build
on:
  workflow_dispatch:
env:
  BUILD_DIR: "C:\\ungoogled-chromium-windows"  
jobs:
  pre-build:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - name: Init
        run: Copy-Item -Path . -Destination "${{ env.BUILD_DIR }}" -Recurse
      - name: Install Dependencies
        run: python -m pip install httplib2
      - name: Run Pre-Build
        id: prebuild
        continue-on-error: true
        run: python pre_build.py --ci
        working-directory: ${{ env.BUILD_DIR }}
      - name: Compress Build Files
        id: compressbuildfiles
        continue-on-error: true
        if: steps.prebuild.outcome == 'success' || steps.prebuild.outcome == 'failure'
        run: 7z a "${{ env.BUILD_DIR }}\artifacts.7z" "${{ env.BUILD_DIR }}\build\src" -m0=LZMA2 -mx=5 -mtc=on -mmt=4 -bt
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        if: steps.compressbuildfiles.outcome == 'success' || steps.compressbuildfiles.outcome == 'failure'
        with:
          name: build-artifact
          path: ${{ env.BUILD_DIR }}\artifacts.7z
          retention-days: 1
          compression-level: 0
          overwrite: true
